car_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from car_inventory.forms import UserLoginForm
from car_inventory.models import User, db, check_password_hash

from flask_login import login_user, logout_user, current_user, login_required


auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid form data, please check your form')

    return render_template('signup.html', form = form)

        
@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    try:
        if request.method =='POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)
        
            logged_user = User.query.filter(User.email == email).first()
            
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in: Via Email/Password', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                #return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid form Data: Please check your form')

    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

car_inventory/site/routes.py
from flask import Blueprint, render_template
from flask_login import login_required 
site = Blueprint('site', __name__, template_folder='site_templates')

"""
IN the above code, some arguments are specified when creating the Blueprint object
This first argument 'site', is the Blueprint's name,
this will be used by flasks routing mechanism.
The second parameter __name__, is the BP's import name,
which flask uses to locate resources
"""

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
@login_required
def profile():
    return render_template('profile.html')

car_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
      $(".close").click(function(){
        $(".alert").hide(1000);
      });
    });
    </script>
    
<title>Car Inventory API</title>
</head>
<body>
    <!-- Nav area here-->
    <nav class="ct-nav">
        <div class="element">
            <img src="../static/Car Images/car-shadow.png" alt="Car Logo">
        </div>


    <!--Nav Items-->
        <div class="element">
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Car API Project</li>
                </a>
                <a href="">
                    <li>Donate</li>
                </a>

               
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                <a href="{{ url_for('auth.logout') }}">
                    <li>Log Out</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="{{ url_for('auth.signup')}}">
                    <li>Sign Up</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!--End of Nav-->
    {% block content %}
    {% endblock content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.5.4/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-beta1/js/bootstrap.min.js"></script>
</body>
</html>

car_inventory/templates/forms.html
<!--Html Produced by Flask Form-->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place email here...") }}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here...")}}
        </fieldset>
        <!--Submit button-->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>